### ISSUE TITLE
livereload not working?

### ISSUE THREAD

**Issue by axelhuizinga** [elsassph/haxe-react-redux#8]
I followed all steps to set-up the examples with livereload but all I get after a code change and
 npm run dev are 2 lines on the dev server started with npm run serve:
2017-11-04 16:58:17 - info:  skip: index.js.map
2017-11-04 16:58:17 - info:  notify: index.js (16 client) s
no reaction in the browser - however on the js console in ff or chrome I get error messages related to the ws connection every minute... firewall for 35729 IN is open

**Comment by elsassph** [comment]
It will depend on what code you change: 
- livereload will only force a react re-render,
- startup / store configuration or mapState aren't re-evaluated.

I pushed an update of the `haxe-modular` npm dependency though as it contains fixes. Re-run `npm install` and `npm run libs` and it should work better generally.

**Comment by axelhuizinga** [comment]
Nice to get a quick response - 
npm install
npm WARN haxe-react-redux@0.0.0 No repository field.

up to date in 2.838s
root@h2410222:/opt/src/sun4.me/haxe-react-redux# npm run libs

> haxe-react-redux@0.0.0 libs /opt/src/sun4.me/haxe-react-redux
> browserify src/libs.js -o bin/libs.js -d

but still no luck:
the  changes I want to see reloaded are edited in Main.hx in the static function pageWrapper Link list at the haxe-react-redux example
It looks like I miss a step or do it in the wrong order - the npm run serve I keep running - after changing the code - I only do  npm run dev? 
any ideas where I could add debug messages to track the mistake?

**Comment by elsassph** [comment]
The thing with live reload is that it's not magic - only split code can reload. In the case if this sample project, the routes component (TodoList, AboutView) can live-reload.

The only thing we could (and should) do is to reload the page when the index JS changes. But that won't be "live".

**Comment by djaonourside** [comment]
@elsassph, for example, I make changes in Main.hx file and auto reloading of index.html works only without -debug flag.  Is it expected behavior?

**Comment by elsassph** [comment]
Hot-reload logic is only included in debug builds.

**Comment by djaonourside** [comment]
Then why livereloadx doesn't reload page after haxe recompile sources when -debug flag **on**?

**Comment by elsassph** [comment]
Changes in the main bundle can't be live updated, and currently the page doesn't auto-refresh when this happens.

**Comment by elsassph** [comment]
https://github.com/elsassph/haxe-modular/issues/10
